[client]
showErrorDetails = "none"

[theme]
primaryColor = "#568EA3"
backgroundColor = "#FFE8D1"

# Color used for almost all text.
textColor = "#826251"

# font = "cool-font, fallback-cool-font, sans-serif"
font = "fallback-cool-font"

baseRadius ="0.5rem"

# The color of the border around elements.
borderColor ="#568EA3"

headingFontSizes = ["3rem", "2.875rem", "2.75rem"]
